version: "3"
services:
  api:
    build: ./api
    container_name: realworld-docker-api
    command: node src/app
    environment:
      - PORT=8080
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    container_name: realworld-docker-db
    volumes:
      - mongodb_api:/data/db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    command: serve -s build -l 3000 -n
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - WDS_SOCKET_PORT=0
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
volumes:
  mongodb_api:
